#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "Cisco-Auditing-Tool"
echo ""
echo "Host/s to scan:"
echo "(type '-h [HOST]' for scanning single host.)"
echo "(type '-f [PATH TO FILE]' for scaning multiple hosts.)"
read HOST
echo ""
echo "Port number (default is 23):"
read PORT
echo ""
echo "Wordlist for community name guessing:"
read WORDLIST
echo ""
echo "Wordlist for password guessing:"
read PASSLIST
echo ""
echo "Check for IOS History bug?"
echo "(type '-i [ioshist]' to enable; Otherwise, press enter.)"
read IOSHISTORYBUG
echo ""
echo "Running..."
echo ""
perl CAT $HOST -p $PORT -w $WORDLIST -a $PASSLIST $IOSHISTORYBUG
echo ""
echo "Running... Done!"
echo ""
read waitforexit
exit 0
