#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "Slowloris: Low bandwidth stress test tool for websites"
echo ""
echo "Target:"
read TARGET
echo ""
echo "Port of webserver (usually 80):"
read PORT
echo ""
echo "Number of sockets to use in the test:"
read SOCKETS
echo ""
echo "Do you want to Randomize user-agents with each request?"
echo "[1] Yes"
echo "[2] No"
read RANDOMIZE
if [ "$RANDOMIZE" == "1" ]; then
	RANDUSERAGENTS="--randuseragents"
else
	RANDUSERAGENTS=""
fi
echo ""
echo "Do you want to use a SOCKS5 proxy for connecting?"
echo "[1] Yes        [i] ROOT REQUIRED!"
echo "[2] No"
read PROXY
if [ "$PROXY" == "1" ]; then
	USEPROXY="--useproxy"
	PROXYH="--proxy-host"
	PROXYP="--proxy-port"
	echo "Enter the host proxy:"
	read PROXYHOST
	echo ""
	echo "Enter the host proxy's Port:"
	read PROXYPORT
fi
echo "Do you want to use HTTPS protocol for the requests?"
echo "[1] Yes"
echo "[2] No"
read HTTPS
if [ "$HTTPS" == "1" ]; then
	USEHTTPS="--https"
else
	USEHTTPS=""
fi
echo ""
echo "Running..."
echo ""
python2 slowloris.py $TARGET --port $PORT --sockets $SOCKETS -v $RANDUSERAGENTS $USEPROXY $PROXYH $PROXYHOST $PROXYP $PROXYPORT $USEHTTPS
echo ""
echo "Running... Done!"
echo ""
read waitforexit
exit $?
