#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "Target URL (e.g. \"http://www.target.com/page.php?id=1\")"
read TARGET
echo ""
echo "Running..."
echo ""
python2 dsss.py --url $TARGET
echo ""
echo "Running... Done!"
echo ""
read waitforexit
exit 0
