#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "Target domain:"
read TARGET
echo ""
echo "Target CMS (wp, dp, jm)"
read CMS
echo ""
echo "Wordlist (Type '$PWD/passwd.txt' for default):"
read WLPATH
echo ""
echo "Running..."
echo ""
python2 angryFuzzer.py --url $TARGET --cms $CMS --wordlist $WLPATH
echo ""
echo "Running... Done!"
echo ""
read waitforexit
exit 0
