#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "Enter the target URL:"
read URL
echo ""
echo "Keyboard layout:"
echo "(Supported: qwerty, azerty, qwertz, dvorak)"
read KEYBOARD
echo ""
echo "Do you want to check domain popularity with Google?"
echo "Type '-p' to enable; Otherwise, press enter."
read POPULARITY
echo ""
echo "Do you want to not resolve DNS?"
echo "Type '-r' to enable; Otherwise, press enter."
read RSLVDNS
echo ""
echo "Do you want to show invalid domain names?"
echo "Type '-i' to enable; Otherwise, press enter."
read INVALID
echo ""
echo "In what way do you want to view the results?"
echo "Type 'human' if you want to view it in human readable form; Otherwise, type CSV."
read VIEW
echo ""
echo "Running..."
echo ""
echo ""
echo ""
chmod +x urlcrazy
./urlcrazy --keyboard $KEYBOARD $POPULARITY $RSLVDNS $INVALID --format $VIEW $URL
echo ""
echo ""
echo ""
echo "Running... Done!"
read waitforexit
exit 0
