#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "The Harvester"
echo ""
echo "Domain to search:"
read TARGET
echo ""
echo "Choose your desired data source:"
echo "(Supported data sources: baidu, bing, bingapi, dogpile, google,"
echo "googleCSE, googleplus, google-profiles, linkedin, pgp, twitter, vhost, yahoo, all)"
read SOURCE
echo ""
echo "In what result number do we start?"
echo "(e.g.: 9 = Start in result number 9)"
echo "(Default: 0)"
read START
echo ""
echo "type '-v' to verify host name via dns resolution and search for virtual hosts."
echo "Otherwise, press enter."
read VERIFYHOSTNAME
echo ""
echo "type '-n' to Perform a DNS reverse query on all ranges discovered."
echo "Otherwise, press enter."
read DNSREVERSE
echo ""
echo "type '-c' to Perform a DNS brute force for the domain name."
echo "Otherwise, press enter."
read DNSBRUTEFORCE
echo""
echo "tpye '-t' to Perform a DNS TLD expansion discovery."
echo "Otherwise, press enter."
read DNSTLD
echo ""
echo "tpye '-h' to use SHODAN database to query discovered hosts."
echo "Otherwise, press enter."
read SHODAN
echo ""
echo "Running..."
echo ""
echo ""
python2 theHarvester.py -d $TARGET -b $SOURCE -s $START $VERIFYHOSTNAME $DNSREVERSE $DNSBRUTEFORCE $DNSTLD $SHODAN
echo ""
echo ""
echo "Running... Done!"
echo ""
read waitforexit
exit 0
