#!/bin/python
# This script will test the Shadow Suite Application Programming Interface (API). 

import API
import time
import sys

API.os.system("clear")
print("Preparing to test API...")
time.sleep(5)
print("Testing API...")
print()
print("Testing error functions via API...")
time.sleep(3)
API.core.error.error0001()
print("Skipping error 0002()...")
API.core.error.error0003()
API.core.error.error0004()
API.core.error.error0005()
API.core.error.error0006()
API.core.error.error0007()
print("Testing find_module() function via API with the valid argument \"sample\"...")
API.Class.find_module("sample")
print("Testing find_module() function via API with the invalid argument \"nsjs25ijw3\"...")
API.Class.find_module("nsjs25ijw3")
print("Testing warning functions via API...")
time.sleep(3)
API.core.error.warning0001()
API.core.error.warning0002()
print("Testing prn_logo() function via API...")
time.sleep(3)
API.core.misc.prn_logo()
print("Testing module_mode() function via API...")
time.sleep(3)
API.core.misc.module_mode()
print("Testing full update via API...")
time.sleep(3)
API.core.update.full_update()
print("Testing deps update via API...")
time.sleep(3)
API.core.update.deps_update()
print("Testing program update via API...")
time.sleep(3)
API.core.update.prog_update()
print("Testing version functions via API...")
time.sleep(3)
API.core.version.number()
print()
API.core.version.type()
print()
API.core.version.codename()
print()
API.core.version.both()
print("Getting API_version variable from API...")
apiversion = API.Class.API_version
print(apiversion)
print("Getting ShadowSuite_ver_num variable from API...")
ver_num = API.Class.ShadowSuite_ver_num
print(ver_num)
print("Getting ShadowSuite_ver_type variable from API...")
ver_type = API.Class.ShadowSuite_ver_type
print(ver_type)
print("Getting ShadowSuite_ver_codename variable from API...")
ver_cn = API.Class.ShadowSuite_ver_codename
print(ver_cn)
print("Calling generate_new_module(cmd) method with a valid argument 'APItest'...")
time.sleep(3)
API.Class.generate_new_module("APItest")
print("Calling list_module() method...")
time.sleep(3)
API.Class.list_module()
print("Calling use_module(module) method with the valid argument \"sample\"...")
time.sleep(3)
API.Class.use_module("sample")
print("Calling use_framework(framework) method with the valid argument \"hakku\"...")
time.sleep(3)
API.Class.use_framework("hakku")
print("Calling use_module(module) method with the invalid argument \"nsjs25ijw3\"...")
time.sleep(3)
API.Class.use_module("nsjs25ijw3")
print("Calling use_framework(framework) method with the invalid argument \"nsjs25ijw3\"...")
time.sleep(3)
API.Class.use_module("nsjs25ijw3")
print("Calling finish() method...")
API.Class.finish()
print("Test finished!!! Now quitting...")
sys.exit(0)
